### ISSUE TITLE
NVM multiple user install on Ubuntu

### ISSUE THREAD

**Issue by a-barbieri** [koenpunt/capistrano-nvm#18]
Might be a dumb question, but if I installed NVM in `/home/myuser/.nvm` how can I set it correctly? 

This doesn't seem to work...
```
# Rails app --> deploy.rb
set :nvm_custom_path, '/home/myuser/.nvm'
```

The documentation isn't so clear and I cannot understand if I am wrong or if the problem I get comes from something else.

**Comment by ljharb** [comment]
https://github.com/koenpunt/capistrano-nvm/blob/2676e9f4278669210d1690e32d1a011901cee081/lib/capistrano/tasks/nvm.cap#L46-L51 suggests that you don't need to set `nvm_custom_path` at all, if `$NVM_DIR` is `$HOME/.nvm`.

**Comment by a-barbieri** [comment]
In myuser `.bashrc` I have
```
export NVM_DIR="/home/myuser/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```
In myuser `.profile` nothing. Should I source `.bashrc` into .profile?

This configuration doesn't work running Capistrano. Unfortunately without a minimum documentation (or help) I cannot understand how to sort this out. Is there anyway to debug it? Definitely I don't know where to go from here...

**Comment by koenpunt** [comment]
Which user is running the Capistrano tasks on the server?

**Comment by a-barbieri** [comment]
I think the Capistrano uses `root`, which is not what I have in my `config/deploy/production.rb`.

On my server I created a user specifically for the app called `myapp_deploy`.

---

Here below my Capistrano configuration.

This is the line in my `config/deploy/production.rb` file:
```
server "123.456.789.000", user: 'myapp_deploy', roles: %w{app web db}

set :branch, 'master'
set :app_domain, "www.myapp.com"
set :deploy_to, '/home/myapp_deploy/production'
```
On my `config/deploy.rb` I have:
```
# Ensure that bundle is used for rake tasks
SSHKit.config.command_map[:rake] = "bundle exec rake"

# config valid only for current version of Capistrano
lock '3.5.0'

# settings
set :application, 'myapp'
set :repo_url, 'git@bitbucket.org:alebarbieri/myapp.git'
set :deploy_via, :remote_cache
set :stages, ['stage', 'production']
set :keep_releases, 5
set :tmp_dir, "/home/myapp_deploy/tmp"

namespace :deploy do

  desc 'Restart application'
  task :restart do
    on roles(:web), in: :sequence, wait: 5 do
      execute :mkdir, '-p', "#{ release_path }/tmp"
      execute :touch, release_path.join('tmp/restart.txt')
    end
  end

  after :publishing, :restart

end

```

**Comment by koenpunt** [comment]
Your `.profile` and/or `.bashrc` are not sourced on deploy, that's why this Capistrano extension is around. And @ljharb's comment is valid; if NVM is installed for the `myapp_deploy` user, you don't have to set `nvm_custom_path`.

**Comment by a-barbieri** [comment]
@koenpunt you are right, and you know why? I've just found out!

My `.bashrc` in `/home/myapp_deploy` has this lines at the bottom:
```
export NVM_DIR="/home/myapp_deploy/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```
That's ok most of the time, but **BE CAREFUL**: Capistrano won't run any `export` command after this command:
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

So the solution is to manually copy/paste the code above it, like this:
```
# Load export path before the following command!
export NVM_DIR="/home/myapp_deploy/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

Thank [you](http://stackoverflow.com/a/29344562/1498118) and [you](https://github.com/capistrano/capistrano/issues/413)

**Comment by koenpunt** [comment]
@a-barbieri the whole point of `capistrano-nvm` is that the source line doesn't have to be in the `.profile` or `.bashrc`, and thus I can't recommend doing it like that.

**Comment by a-barbieri** [comment]
...disappointing, that was defenitely working... so how can I achieve the same result?

**Comment by koenpunt** [comment]
What errors do you get? Or what in your deploy is using nvm?

**Comment by a-barbieri** [comment]
The error is:
```
00:56 deploy:assets:precompile
      01 /usr/local/rvm/bin/rvm default do bundle exec rake assets:precompile
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
      01 Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs…
```
Which is used by `deploy:assets:precompile`.

**Comment by koenpunt** [comment]
Try adding `rake` to `nvm_map_bins`:

```rb
set :nvm_map_bins, fetch(:nvm_map_bins, []).push 'rake'
```

**Comment by a-barbieri** [comment]
Rails didn't like the string at the end of the line so I added brackets to it `push('rake')`. Anyhow it didn't work. Same as before.

**Comment by koenpunt** [comment]
Can you set `log_level` to `debug` and post your (redacted) capistrano.log here?

```rb
set :log_level, :debug
```

**Comment by a-barbieri** [comment]
@koenpunt: you can find it [here](https://gist.github.com/a-barbieri/6158730a893f360b8bf0828641f259fc#file-capistrano-log-L119-L122).

**Comment by koenpunt** [comment]
I don't see nvm anywhere in the logs, could it be that you forgot to add `require 'capistrano/nvm'` to your `Capfile`?

**Comment by a-barbieri** [comment]
Yes, that's it.
I've been so overwhelmed by the amount of lines which fill my configuration files that I repeatedly mistaken  `require 'capistrano/rvm'` with `require 'capistrano/nvm'`. Defenitely too similar...

Thank you @koenpunt.

**Comment by a-barbieri** [comment]
Sorry @koenpunt to bother you again, but if the deploy now works fine, Phusion Passenger is now complaining that it cannot find node. Apparently [this solution](https://github.com/koenpunt/capistrano-nvm/issues/18#issuecomment-225826884) solve the problem, but that means it's misconfigured somewhere. 

I'm trying to find a solution, and as soon as I have it, I'll post it here for anyone who have the same issue.

**Comment by koenpunt** [comment]
You should specify the path to the node version in your server configuration using  `passenger_nodejs <path/to/node>` (nginx) or `PassengerNodejs <path/to/node>;` (Apache)

**Comment by koenpunt** [comment]
And you could try to set that to `~/.nvm/nvm-exec node`, although I think you'll have to set a actual path to the node binary, something like ~/.nvm/versions/vx.x.x/bin/node

**Comment by a-barbieri** [comment]
> You should specify the path to the node binary in your server configuration using `passenger_nodejs <path/to/node>;` (nginx) or `PassengerNodejs <path/to/node>;` (Apache)

Yep. That does it.
```
server {
        listen 80;
        server_name www.myapp.com;
        passenger_enabled on;
        passenger_app_env production;
        passenger_nodejs /home/myapp_deploy/.nvm/versions/node/v6.2.0/bin/node;
        root /home/myapp_deploy/production/current/public;
}
```
