### ISSUE TITLE
capistrano-nvm looks for nodejs in wrong directory

### ISSUE THREAD

**Issue by Quintasan** [koenpunt/capistrano-nvm#7]
I've been trying to get my application deployed with Capistrano using nvm but it fails the `nvm:validate` task:
`ERROR nvm: v0.12.5 is not installed or not found in $HOME/.nvm/v0.12.5`
The problem is that NVM installs node to `.nvm/versions/node/<version>` instead

**Comment by koenpunt** [comment]
Hm, could make that configurable. Previous versions of NVM used the root `.nvm` directory. But somewhere before the `nvm.sh` file passed the 1000 lines of source code I stopped using it.

**Comment by MakotoTheKnight** [comment]
+1 to this; I'd rather be able to specify where it lives than it have assumptions about it.

**Comment by dchersey** [comment]
Looking at the source, I found that I could specify
set :nvm_node_path, '/home/rails/.nvm/versions/node/v4.2.1' in my deploy/environment.rb 
and it successfully finds the node location.

**Comment by koenpunt** [comment]
If you set `nvm_custom_path` to `$HOME/.nvm/versions/node` it should work:

```rb
set : nvm_custom_path, "$HOME/.nvm/versions/node"
```

**Comment by dchersey** [comment]
Thanks!

**Comment by koenpunt** [comment]
Released as v0.0.6: https://github.com/koenpunt/capistrano-nvm/releases/tag/v0.0.6
